### ISSUE TITLE
503 Service Unavailable after some time running the game

### ISSUE THREAD

**Issue by xfactores** [texel-sensei/CM3D2.AutoTranslate#10]
I'm using TranslationPlus and after some time running the game I think the translate.googleapis.com site block my IP from sending more request and just send me a 503 Service Unavailable error. Here's one of the errors :

[AutoTranslate] [1.3.3] [Error]: 503 Service Unavailable
Log @   at System.Environment.get_StackTrace()
   at CM3D2.AutoTranslate.Plugin.Logger.LogError(System.Object msg)
   at CM3D2.AutoTranslate.Plugin.GoogleTranslationModule+<TranslateGoogle>d__9.MoveNext()
   at CM3D2.AutoTranslate.Plugin.CoroutineEx+<Run>d__13.MoveNext()
   at UnityEngine.SetupCoroutine.InvokeMoveNext(IEnumerator enumerator, IntPtr returnValueAddress)

**Comment by lightningterror** [comment]
Might as well read this, it's the same issue https://github.com/bbepis/XUnity.AutoTranslator/issues/5
