### ISSUE TITLE
503 Service Unavaliable

### ISSUE THREAD

**Issue by KiiOO** [texel-sensei/CM3D2.AutoTranslate#11]
[AutoTranslate] [1.3.3] [Error]: 503 Service Unavailable
Log @   at System.Environment.get_StackTrace()
   at CM3D2.AutoTranslate.Plugin.Logger.LogError(System.Object msg)
   at CM3D2.AutoTranslate.Plugin.GoogleTranslationModule+<TranslateGoogle>d__9.MoveNext()
   at CM3D2.AutoTranslate.Plugin.CoroutineEx+<Run>d__13.MoveNext()
   at UnityEngine.SetupCoroutine.InvokeMoveNext(IEnumerator enumerator, IntPtr returnValueAddress)

**Comment by KiiOO** [comment]
Nevermind saw the previous post
